spring:
  application:
    name: warehouse-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

aws:
  sqs:
    queue:
      stock-change-event-queue: https://sqs.us-east-1.amazonaws.com/851725329993/stock-change-queue